export const INVALID_ARG = 'invalid arg'
export const INVALID_RESPONSE = 'invalid response'
export const INVALID_USER_ADDR = 'invalid user addr'
export const INVALID_CONTRACT_ADDR = 'invalid contract addr'

export const NETWORK_ERROR = 'network error'
export const SERVER_ERROR = 'server error'
export const INVALID_REQUEST = 'invalid request'
export const INVALID_CONTRACT = 'invalid contract'
export const REQUEST_TIMEOUT = 'request timeout'
export const TX_TIMEOUT = 'tx timeout'
export const PAY_ID_REG_FAILED = 'pay id reg failed'

export const TX_REJECTED_BY_USER = 'tx rejected by user'
export const TX_STATUS_UNKNOWN = 'tx status unknown'
export const TX_FAILED = 'tx failed'
export const CALL_FAILED = 'call failed'

export const EXTENSION_NOT_INSTALLED = 'extension not installed'
export const EXTENSION_TIMEOUT = 'extension timeout'
export const EXTENSION_NO_WALLET = 'extension no wallet'
